function applyHomeName() { const heroTitle = document.getElementById('story-title'); if (heroTitle) heroTitle.innerHTML = 'Story Time<br><em>Priya ⭐</em>'; }
const cosmicStyles = document.createElement('link');
cosmicStyles.rel = 'stylesheet';
cosmicStyles.href = 'css/cosmic.css';
document.head.appendChild(cosmicStyles);
const visualScript = document.createElement('script');
visualScript.src = 'js/visuals.js';
document.body.appendChild(visualScript);
const siteName = 'Story Time Priya ⭐';
function applySiteName() { document.querySelectorAll('.brand span:last-child').forEach(element => element.textContent = siteName); document.querySelectorAll('.site-footer span:first-child').forEach(element => element.textContent = `© 2026 ${siteName} · Elian Vale`); if (document.body.dataset.page !== 'reader') document.title = `${siteName} | A serialized story`; }
function validChapters() { return chapters.filter(chapter => chapter && Number.isInteger(chapter.id) && chapter.title && ['published','upcoming','draft'].includes(chapter.status)); }
function publishedChapters() { return validChapters().filter(chapter => chapter.status === 'published').sort((a,b) => a.id - b.id); }
function chapterById(id) { return validChapters().find(chapter => chapter.id === id); }
function showToast(message) { const toast = document.getElementById('toast'); if (!toast) return; toast.textContent = message; toast.classList.add('show'); setTimeout(() => toast.classList.remove('show'), 2400); }
function renderHeader() { const header = document.getElementById('site-header'); if (!header) return; const page = document.body.dataset.page; header.className = 'site-header wrap'; header.innerHTML = `<a class="brand" href="index.html"><span class="brand-mark">LT</span><span>The House at Low Tide</span></a><nav class="main-nav" aria-label="Main navigation"><a href="index.html" ${page==='home'?'aria-current="page"':''}>Home</a><a href="chapters.html" ${page==='chapters'?'aria-current="page"':''}>Chapters</a><a href="about.html" ${page==='about'?'aria-current="page"':''}>About</a></nav><div class="header-actions"><a href="chapters.html#bookmarks">Bookmarks</a><button class="menu-toggle" type="button" aria-label="Open menu" aria-expanded="false">☰</button></div>`; const toggle=header.querySelector('.menu-toggle'); toggle.addEventListener('click',()=>{const nav=header.querySelector('.main-nav'); const open=nav.classList.toggle('open'); toggle.setAttribute('aria-expanded',open); toggle.setAttribute('aria-label',open?'Close menu':'Open menu');}); }
function renderFooter() { const footer=document.getElementById('site-footer'); if(footer) footer.innerHTML='<footer class="site-footer wrap"><div class="footer-inner"><span>© 2026 The House at Low Tide · Elian Vale</span><nav class="footer-nav" aria-label="Footer navigation"><a href="index.html">Home</a><a href="chapters.html">Chapters</a><a href="about.html">About</a></nav></div></footer>'; }
function renderHome() { const list=document.getElementById('latest-chapters'); if(!list) return; const recent=publishedChapters().slice(-2).reverse(); list.innerHTML=recent.map(chapter => `<article class="chapter-card"><span class="chapter-number">CHAPTER ${String(chapter.id).padStart(2,'0')}</span><h3>${chapter.title}</h3><p>${chapter.subtitle}</p><div class="card-footer"><span>${formatDate(chapter.date)}</span><a href="reader.html?chapter=${chapter.id}">Read chapter →</a></div></article>`).join(''); document.getElementById('published-count').textContent=publishedChapters().length; const latest=publishedChapters().at(-1); document.getElementById('last-updated').textContent=latest ? formatDate(latest.date).replace(', 2026','') : '—'; const last=getLastChapter(); const continueLink=document.getElementById('continue-reading'); if(last && chapterById(last)?.status==='published'){continueLink.hidden=false; document.getElementById('start-reading').textContent='Start from chapter one ↗';} }
renderHeader(); renderFooter(); renderHome(); applySiteName(); applyHomeName();