function syncReaderWidth() { const width = { narrow: '620px', normal: '730px', wide: '850px' }[getSettings().readerWidth] || '730px'; document.querySelectorAll('.chapter-body,.reader-navigation').forEach(element => element.style.maxWidth = width); }
document.querySelectorAll('[data-setting="readerWidth"]').forEach(button => button.addEventListener('click', syncReaderWidth));
syncReaderWidth();
function chapterById(id) { return chapters.find(chapter => chapter && chapter.id === id); }
function publishedChapters() { return chapters.filter(chapter => chapter && chapter.status === 'published').sort((a, b) => a.id - b.id); }
function showToast(message) { const toast = document.getElementById('toast'); if (!toast) return; toast.textContent = message; toast.classList.add('show'); setTimeout(() => toast.classList.remove('show'), 2400); }
const requestedId=Number(new URLSearchParams(window.location.search).get('chapter')); const requestedChapter=chapterById(requestedId); const reader=document.getElementById('reader-content'); const error=document.getElementById('reader-error');
function renderReaderError(message) { error.hidden=false; error.innerHTML=`<p class="eyebrow">The journal</p><h1>Chapter not found</h1><p>${message}</p><a class="button button-primary" href="chapters.html">Back to chapters <span>→</span></a>`; }
function renderContent(content) { const body=document.getElementById('chapter-body'); if(!Array.isArray(content)||!content.length){body.innerHTML='<p>This chapter is still being written. Check back when the tide turns.</p>';return;} content.forEach(item=>{const element=document.createElement(item?.type==='scene-break'?'div':'p'); if(item?.type==='scene-break'){element.className='scene-break';element.textContent='· · ·';} else element.textContent=typeof item==='string'?item:(item?.text || ''); body.appendChild(element);}); }
function renderNavigation() { const list=publishedChapters(); const index=list.findIndex(chapter=>chapter.id===requestedId); const previous=list[index-1]; const next=list[index+1]; document.getElementById('reader-navigation').innerHTML=`<a href="${previous?`reader.html?chapter=${previous.id}`:'#'}" aria-disabled="${!previous}">← ${previous?previous.title:'First chapter'}</a><a class="nav-center" href="chapters.html">All chapters</a><a href="${next?`reader.html?chapter=${next.id}`:'#'}" aria-disabled="${!next}">${next?next.title:'More soon'} →</a>`; }
function setupReader() { if(!requestedChapter){renderReaderError('The chapter you are looking for does not exist or is not available yet.');return;} if(requestedChapter.status!=='published'){renderReaderError('This chapter is not published yet. Come back when the tide turns.');return;} reader.hidden=false; document.title=`${requestedChapter.title} — Chapter ${requestedChapter.id} | The House at Low Tide`; document.getElementById('reader-number').textContent=`Chapter ${String(requestedChapter.id).padStart(2,'0')}`; document.getElementById('reader-title').textContent=requestedChapter.title; document.getElementById('reader-subtitle').textContent=requestedChapter.subtitle || ''; document.getElementById('reader-date').textContent=`Published ${formatDate(requestedChapter.date)}`; renderContent(requestedChapter.content); renderNavigation(); const bookmark=document.getElementById('bookmark-button'); const syncBookmark=()=>{const active=getBookmarks().includes(requestedId);bookmark.setAttribute('aria-pressed',active);bookmark.innerHTML=active?'★ <span>Bookmarked</span>':'☆ <span>Bookmark</span>';}; bookmark.addEventListener('click',()=>{const added=toggleBookmark(requestedId);syncBookmark();showToast(added?'Bookmark added':'Bookmark removed');}); syncBookmark(); const settingsDialog=document.getElementById('settings-dialog'); document.getElementById('settings-button').addEventListener('click',()=>settingsDialog.showModal()); document.addEventListener('keydown',event=>{if(event.key==='Escape'&&settingsDialog.open)settingsDialog.close();}); document.getElementById('share-button').addEventListener('click',shareChapter); setupReadingProgress(); }
async function shareChapter(){const url=window.location.href; try{if(navigator.share) await navigator.share({title:requestedChapter.title,text:requestedChapter.subtitle,url}); else await copyLink(url);}catch(error){if(error.name!=='AbortError')showToast('Sharing was unavailable');}}
async function copyLink(url){try{if(navigator.clipboard) await navigator.clipboard.writeText(url); else throw new Error('clipboard unavailable');showToast('Chapter link copied');}catch{const field=document.createElement('textarea');field.value=url;document.body.appendChild(field);field.select();document.execCommand('copy');field.remove();showToast('Chapter link copied');}}
function setupReadingProgress(){const fill=document.getElementById('reading-progress-fill');const backTop=document.getElementById('back-top');const saved=safeProgress()[requestedId]?.position || 0; if(saved>100){const prompt=document.createElement('div');prompt.className='resume-prompt';prompt.innerHTML='<span>Continue where you left off?</span><button type="button">Continue</button><button type="button">Start over</button>';document.body.prepend(prompt);prompt.querySelector('button').onclick=()=>{window.scrollTo({top:saved});prompt.remove()};prompt.querySelectorAll('button')[1].onclick=()=>prompt.remove();} const update=()=>{const scrollable=document.documentElement.scrollHeight-window.innerHeight;const percent=scrollable>0?(window.scrollY/scrollable)*100:0;fill.style.width=`${percent}%`;backTop.classList.toggle('visible',window.scrollY>500);saveChapterProgress(requestedId,percent,window.scrollY);}; window.addEventListener('scroll',update,{passive:true});backTop.addEventListener('click',()=>window.scrollTo({top:0,behavior:'smooth'})); }
setupReader();